#프로젝트 이름 설정 예시
#spring.application.name=basic

#서버 포트 기본값은 8080입니다
#server.port=8080


server:
  port: 8080

spring:
  # 아래는 jdbc의 기본 db 관련 설정인데, jdbc 뿐만 아니라 mybatis / jpa 등 spring의 대부분의 DB 기술에 동일하게 사용
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1234

#    mapper파일(mybatis의 쿼리파일)의 위치를 명시하고 scan, 기본적으로 resource 풀더는 default
mybatis:
  mapper-locations: classpath:/Mapper/**/*.xml